apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: kubetrail
deploy:
  helm:
    releases:
    - name: kubetrail
      chartPath: config/charts/kubetrail
      namespace: skaffold
      values:
        image: kubetrail
